#!/usr/bin/env bash
vpn() {
	nmcli -t -f NAME,TYPE connection show  --active | grep 'vpn$' | sed 's/\(.*\):vpn/\1/' | paste -sd "," -
}

case $BLOCK_BUTTON in
  3) xfce4-terminal -e 'nmtui' & # right click, mute/unmute
esac
vpn


